[project]
name = "ross-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ross-rotordynamics>=1.6.1",
    "ruff>=0.11.11",
]
